# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  - trigger: ":ai_japanese"
    replace: "Your task is to take the text provided and translate it into clear and formal academic Japanese, preserving the original meaning and style as closely as possible"
  - trigger: ":ai_proofread"
    replace: "Your task is to take the text provided and rewrite it into a clear, grammatically correct version while preserving the original meaning as closely as possible. Correct any spelling mistakes, punctuation errors, verb tense issues, word choice problems, and other grammatical mistakes. But do not correct something that is not a mistake but just a different style or preference. Use bold formatting in markdown to emphasize the edited portions of the English text. Do not break the latex format. The phrase or tone must follow the engineering or scientific style. Note that if the correction is minor, you may not need to make any changes and just say 'No errors found.'"
  - trigger: ":ai_fluent"
    replace: "Your task is to take the text provided and rewrite it into a clear, grammatically correct version while preserving the original meaning as closely as possible. Correct any spelling mistakes, punctuation errors, verb tense issues, word choice problems, and other grammatical mistakes. Also, please make the sentences fluent and natural to the extent not changing the sentence structure. Use bold formatting in markdown to emphasize the edited portions of the English text. Do not break the latex format. The phrase or tone must follow the engineering or scientific style. Note that if the correction is minor, you may not need to make any changes and just say 'No errors found.'"
  - trigger: ":ai_rewrite"
    replace: "Your task is to take the text provided and perform structure-level and sentence-level revisions to improve clarity, coherence, and overall readability while maintaining the original meaning. Focus on enhancing sentence structure, word choice, and logical flow. Consider splitting long, complex sentences into shorter, more manageable ones. Eliminate redundancies and unnecessary words. Use transitions to improve the connection between ideas. If needed, rearrange sentences to create a more logical progression. Use bold formatting in markdown to emphasize the edited portions of the English text. Preserve the original author's voice and style as much as possible. Do not break the latex format. The phrase or tone must follow the engineering or scientific style."
  - trigger: ":ai_revise"
    replace: "Your task is to take the text provided and perform sentence-level revisions to improve clarity, coherence, and overall readability while maintaining the original meaning. Focus on enhancing sentence structure, word choice, and logical flow. Consider splitting long, complex sentences into shorter, more manageable ones. Eliminate redundancies and unnecessary words. Use transitions to improve the connection between ideas. If needed, rearrange sentences to create a more logical progression. Use bold formatting in markdown to emphasize the edited portions of the English text. Preserve the original author's voice and style as much as possible. Do not break the latex format. The phrase or tone must follow the engineering or scientific style."

  - trigger: ":ai_concise"
    replace: "Your task is to take the text provided and perform sentence-level revisions to improve conciseness, keeping the original information intact. Focus on enhancing sentence structure, word choice, and logical flow. If needed, rearrange sentences to create a more logical progression. Use bold formatting in markdown to emphasize the edited portions of the English text. Preserve the original author's voice and style as much as possible. Do not break the latex format. The phrase or tone must follow the engineering or scientific style. Please avoid writing a too long sentence."

  - trigger: ":ai_review"
    replace: "As an AI with a deep understanding of your research topic, you will critically review the following text related to your work. You will analyze it for two specific issues and enumerate them as many as possible with concise descriptions. 1) Leap-of-logic fallacies: You will meticulously identify any instances where the text makes illogical leaps or draws conclusions unsupported by the provided premises or evidence. 2) Undefined words and symbols: You will carefully identify any technical terms, field-specific jargon, or math symbols used in the text without proper definition or contextual explanation. Please note that You will critique and provide feedback as if you were a strict peer reviewer assessing your work for publication. Expect a rigorous and unforgiving evaluation of your text."

  - trigger: ":ai_defcheck"
    replace: "As an AI with a deep understanding of your research topic, please provide a list of technical terms, field-specific jargon, or math symbols used in the text without proper definition or contextual explanation. Please note that you will critique and provide feedback as if you were a strict peer reviewer assessing your work for publication. Expect a rigorous and unforgiving evaluation of your text."

  - trigger: ":ai_guess"
    replace: "The pasted text that I wrote is mimicking a specific native tongue writer. Could you infer which language I am mimicking? This can often be inferred from the collocation of words, grammatical preferences, and mistakes. The reason I need this information is to basically brush up my English writing. Then, please enumerate possible modifications to enhance the text to sound more like a native English speaker."

  - trigger: ":ai_mimic"
    replace: "The pasted text was written by a Japanese native speaker. Could you identify any indicators typical of Japanese speakers, not limited to mistakes, but also including word collocations, grammatical preferences, and so on? Then, rewrite the text in a more naturally native English style. Use bold formatting in Markdown to emphasize the edited portions of the English text. Do not alter the LaTeX format."

  - trigger: ":ai_read"
    replace: "Please read the attached PDF to prepare for the upcoming query. Do not respond to this message now."
